#!/bin/bash

set -ex

TAG="data-collector-build"
docker build -t "$TAG" .
docker run --rm --entrypoint="./build-linux-entrypoint" -v $(pwd)/dist:/usr/src/app/dist -v $(pwd)/build:/usr/src/app/build "$TAG"
